language: node_js
node_js:
  - "8.11"
addons:
  postgresql: "10"
before_script:
  - npm install -g knex
  - npm install knex
  - psql -c 'create database qs_node' -U postgres
  - psql -c 'create database qs_node_test' -U postgres
  - NODE_ENV=test knex migrate:latest
